category_dict = {
    "Auto, Rad & Boot": "c210",
    "Autos": "c216",
    "Autoteile & Reifen": "c223",
    "Boote & Bootszubehör": "c211",
    "Fahrräder & Zubehör": "c217",
    "Motorräder & Motorroller": "c305",
    "Motorradteile & Zubehör": "c306",
    "Nutzfahrzeuge & Anhänger": "c276",
    "Reparaturen & Dienstleistungen": "c280",
    "Wohnwagen & -mobile": "c220",
    "Weiteres Auto, Rad & Boot": "c241",
    "Elektronik": "c161",
    "Audio & Hifi": "c172",
    "Dienstleistungen Elektronik": "c226",
    "Foto": "c245",
    "Handy & Telefon": "c173",
    "Haushaltsgeräte": "c176",
    "Konsolen": "c279",
    "Notebooks": "c278",
    "PCs": "c228",
    "PC-Zubehör & Software": "c225",
    "Tablets & Reader": "c285",
    "TV & Video": "c175",
    "Videospiele": "c227",
    "Weitere Elektronik": "c168",
    "Haus & Garten": "c80 ",
    "Badezimmer": "c91",
    "Büro": "c93 ",
    "Dekoration": "c246 ",
    "Dienstleistungen Haus & Garten": "c239 ",
    "Gartenzubehör & Pflanzen": "c89",
    "Heimtextilien": "c90",
    "Heimwerken": "c84",
    "Küche & Esszimmer": "c86",
    "Lampen & Licht": "c82 ",
    "Schlafzimmer": "c81",
    "Wohnzimmer": "c88",
    "Weiteres Haus & Garten": "c87",
    "Jobs": "c102",
    "Ausbildung": "c118",
    "Bau, Handwerk & Produktion": "c111",
    "Büroarbeit & Verwaltung": "c114",
    "Gastronomie & Tourismus": "c110",
    "Kundenservice & Call Center": "c105",
    "Mini- & Nebenjobs": "c107",
    "Praktika": "c125",
    "Sozialer Sektor & Pflege": "c123",
    "Transport, Logistik & Verkehr": "c247",
    "Vertrieb, Einkauf & Verkauf": "c117",
    "Weitere Jobs": "c109",
    "Nachbarschaftshilfe": "c400",
    "Dienstleistungen": "c297",
    "Reise & Event": "c294",
    "Weitere Dienstleistungen": "c298",
    "Familie, Kind & Baby": "c171",
    "Altenpflege": "c236",
    "Baby- & Kinderkleidung": "c221",
    "Baby- & Kinderschuhe": "c191",
    "Baby-Ausstattung": "c258",
    "Babyschalen & Kindersitze": "c21",
    "Babysitter & Kinderbetreuung": "c237",
    "Kinderwagen & Buggys": "c25",
    "Kinderzimmermöbel": "c20",
    "Spielzeug": "c23",
    "Weiteres Familie, Kind & Baby": "c18",
    "Haustiere": "c130",
    "Fische": "c138",
    "Hunde": "c134",
    "Katzen": "c136",
    "Kleintiere": "c132",
    "Pferde": "c139",
    "Reptilien": "c244",
    "Tierbetreuung & Training": "c133",
    "Vermisste Tiere": "c283",
    "Vögel": "c243",
    "Zubehör": "c313",
    "Weitere Haustiere": "c131",
    "Mode & Beauty": "c153",
    "Acessoires & Schmuck": "c156",
    "Beauty & Gesundheit": "c224",
    "Damenbekleidung": "c154",
    "Damenschuhe": "c159",
    "Herrenbekleidung": "c160",
    "Herrenschuhe": "c158",
    "Weiteres Mode & Beauty": "c155",
    "Unterricht & Kurse": "c235",
    "Computerkurse": "c260",
    "Kochen & Backen": "c263",
    "Kunst & Gestaltung": "c264",
    "Musik & Gesang": "c262",
    "Nachhilfe": "c268",
    "Sportkurse": "c261",
    "Sprachkurse": "c271",
    "Tanzkurse": "c267",
    "Weiterbildung": "c266",
    "Weitere Unterricht & Kurse": "c270",
    "Eintrittskarten & Tickets": "c231",
    "Bahn & ÖPNV": "c286",
    "Comedy & Kabarett": "c254",
    "Gutscheine": "c287",
    "Kinder": "c252",
    "Konzerte": "c255",
    "Sport": "c257",
    "Theater & Musical": "c251",
    "Weitere Eintrittskarten & Tickets": "c256",
    "Freizeit, Hobby & Nachbarschaft": "c185",
    "Esoterik & Spirituelles": "c232",
    "Essen & Trinken": "c248",
    "Freizeitaktivitäten": "c187",
    "Handarbeit, Basteln & Kunsthandwerk": "c282",
    "Kunst & Antiquitäten": "c240",
    "Künstler & Musiker": "c191",
    "Modellbau": "c249",
    "Reise & Eventservices": "c233",
    "Sammeln": "c234",
    "Sport & Camping": "c230",
    "Trödel": "c250",
    "Verloren & Gefunden": "c189",
    "Weiteres Freizeit, Hobby & Nachbarschaft": "c242",
    "Immobilien": "c195",
    "Auf Zeit & WG": "c199",
    "Eigentumswohnungen": "c196",
    "Ferien- & Auslandsimmobilien": "c275",
    "Garagen & Stellplätze": "c197",
    "Gewerbeimmobilien": "c277",
    "Grundstücke & Gärten": "c207",
    "Häuser zum Kauf": "c208",
    "Häuser zur Miete": "c205",
    "Mietwohnungen": "c203",
    "Umzug & Transport": "c238",
    "Weitere Immobilien": "c198",
    "Musik, Filme & Bücher": "c73",
    "Bücher & Zeitschriften": "c76",
    "Büro & Schreibwaren": "c281",
    "Comics": "c284",
    "Fachbücher, Schule & Studium": "c77",
    "Film & DVD": "c79",
    "Musik & CDs": "c78",
    "Musikinstrumente": "c74",
    "Weitere Musik, Filme & Bücher": "c75",
    "Verschenken & Tauschen": "c272",
    "Tauschen": "c273",
    "Verleihen": "c274",
    "Verschenken": "c192",
}
